package actions

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/google/go-github/v69/github"
)

var (
	client     = github.NewClient(nil)
	ErrNoToken = errors.New("actions: no GH_TOKEN")
)

// In our previous design, each platform should generate *_{OS}_{Arch}.go file
// Feb 12th, this design revoked, still keep the code.
// var currentSuffix = runtime.GOOS + "_" + runtime.GOARCH

func must(err error) {
	if err != nil {
		panic(err)
	}
}

// envToString converts a env map to string
func envToString(envm map[string]string) string {
	var env []string

	for name, value := range envm {
		env = append(env, fmt.Sprintf("%s=%s", name, value))
	}
	return strings.Join(env, "\n")
}

// Setenv sets the value of the Github environment variable named by the key.
func Setenv(envm map[string]string) {
	env, err := os.OpenFile(os.Getenv("GITHUB_ENV"), os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
	// should never happen,
	// it means current runtime is not Github actions if there's any errors
	must(err)

	env.WriteString(envToString(envm))

	// make sure we write it to the GITHUB_ENV
	env.Close()
}

// Changes returns the changed files in current PR,
// which depends on ALL_CHANGED_FILES generated by tj-actions/changed-files action,
// if there's no content in ALL_CHANGED_FILES, it panic.
func Changes() []string {
	changes := os.Getenv("ALL_CHANGED_FILES")
	if changes == "" {
		panic("cannot find changes file!")
	}
	return strings.Fields(changes)
}

func BranchExist(branchName string) (bool, error) {
	token := os.Getenv("GH_TOKEN")
	if token == "" {
		return false, ErrNoToken
	}
	ctx, cancel := context.WithTimeout(context.TODO(), 30*time.Second)
	defer cancel()

	authClient := client.WithAuthToken(token)
	branch, resp, err := authClient.Repositories.GetBranch(ctx,
		os.Getenv("GITHUB_REPOSITORY_OWNER"),
		os.Getenv("GITHUB_REPOSITORY"),
		branchName, 0,
	)

	exists := err == nil &&
		branch != nil &&
		resp.StatusCode == http.StatusOK

	return exists, err
}

func CreateBranch(branchName, tag string) error {
	ret, err := exec.Command("git", "checkout", "-b", branchName, tag).CombinedOutput()
	if err != nil {
		return errors.New(string(ret))
	}
	ret, err = exec.Command("git", "push", "-u", "origin", branchName).CombinedOutput()
	if err != nil {
		return errors.New(string(ret))
	}
	return nil
}

func IsAssociatedWithPullRequest(sha string) (bool, error) {
	token := os.Getenv("GH_TOKEN")
	if token == "" {
		return false, ErrNoToken
	}
	ctx, cancel := context.WithTimeout(context.TODO(), 30*time.Second)
	defer cancel()

	authClient := client.WithAuthToken(token)
	pulls, resp, err := authClient.PullRequests.ListPullRequestsWithCommit(ctx,
		os.Getenv("GITHUB_REPOSITORY_OWNER"),
		os.Getenv("GITHUB_REPOSITORY"),
		sha, &github.ListOptions{},
	)

	ok := err == nil &&
		resp.StatusCode == http.StatusOK &&
		len(pulls) > 0

	return ok, err
}
